=== delasport-org/odds-delivery-feed-consumer-example-php/documentation-resources/settlements/settlements-json-schema.json
{
  "type": "object",
  "additionalProperties": false,
  "title": "Settlement Sports Stream Message",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Origin": {
      "type": "object",
      "properties": {
        "environment": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "type": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "stream": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "version": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "League": {
      "type": "object",
      "properties": {
        "format": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "title": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "LiveGamePeriod": {
      "type": "object",
      "properties": {
        "name": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "OddOddsHistory": {
      "type": "object",
      "properties": {
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "value": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "number"
            }
          ]
        },
        "key": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "isValid": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "boolean"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "EventInfo": {
      "type": "object",
      "properties": {
        "country": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Country"
            }
          ]
        },
        "teams": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Teams"
            }
          ]
        },
        "league": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/League"
            }
          ]
        },
        "liveGamePeriod": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/LiveGamePeriod"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "state": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "liveMinute": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        },
        "marketsCount": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        },
        "sport": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Sport"
            }
          ]
        },
        "startDate": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "status": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "timeRange": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "LineInfo": {
      "type": "object",
      "properties": {
        "lineEntity": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/LineEntity"
            }
          ]
        },
        "isValid": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "boolean"
            }
          ]
        },
        "index": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "gamePeriod": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/GamePeriod"
            }
          ]
        },
        "marketType": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/MarketType"
            }
          ]
        },
        "updatedAt": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "spread": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "number"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "LineEntity": {
      "type": "object",
      "properties": {
        "name": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Sport": {
      "type": "object",
      "properties": {
        "title": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Country": {
      "type": "object",
      "properties": {
        "title": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Teams": {
      "type": "object",
      "properties": {
        "away": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Team"
            }
          ]
        },
        "home": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Team"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "GamePeriod": {
      "type": "object",
      "properties": {
        "name": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Team": {
      "type": "object",
      "properties": {
        "name": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "MarketType": {
      "type": "object",
      "properties": {
        "name": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "eventInfo": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "$ref": "#/definitions/EventInfo"
        }
      ]
    },
    "lineInfo": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "$ref": "#/definitions/LineInfo"
        }
      ]
    },
    "origin": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "$ref": "#/definitions/Origin"
        }
      ]
    },
    "id": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "odd": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "$ref": "#/definitions/OddOddsHistory"
        }
      ]
    },
    "status": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "timestamp": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    }
  }
}

=== delasport-org/odds-delivery-feed-consumer-example-php/documentation-resources/settlements/settlements-sample.json
{
  "origin": {
    "stream": "sport",
    "type": "settlement",
    "environment": "prod",
    "version": "1.0.0"
  },
  "id": "422796af-4661-11ee-8243-42010a9c003a",
  "status": "win",
  "eventInfo": {
    "id": "6540840",
    "state": "live",
    "status": "running",
    "liveGamePeriod": {
      "name": "2h"
    },
    "liveMinute": 1,
    "marketsCount": 5,
    "startDate": "2023-08-29 11:30:00+0000",
    "timeRange": "today",
    "sport": {
      "id": "1",
      "title": "Football",
      "key": "soccer"
    },
    "country": {
      "id": "1",
      "title": "International"
    },
    "league": {
      "id": "16596",
      "title": "Esoccer Friendly - 15 mins play"
    },
    "teams": {
      "home": {
        "id": "206115",
        "name": "Everton Virtual",
        "color": ""
      },
      "away": {
        "id": "208486",
        "name": "Juventus Virtual",
        "color": ""
      }
    }
  },
  "lineInfo": {
    "id": "476916281",
    "index": 2,
    "updatedAt": "2023-08-29 11:44:24.222+0000",
    "marketType": {
      "id": "3",
      "name": "Over/Under"
    },
    "lineEntity": {
      "id": "1",
      "name": "Goals"
    },
    "gamePeriod": {
      "id": "2",
      "name": "Full Time"
    },
    "isValid": false,
    "spread": 1
  },
  "odd": {
    "id": "e_3404677826",
    "key": "over",
    "value": 1.583,
    "isValid": true
  },
  "timestamp": "2023-08-29 11:58:21.017+0000"
}
