=== delasport-org/odds-delivery-feed-consumer-example-php/documentation-resources/events/events-json-schema.json
{
  "type": "object",
  "additionalProperties": false,
  "title": "Event Sports Stream Message",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Origin": {
      "type": "object",
      "properties": {
        "environment": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "type": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "stream": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "version": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Sport": {
      "type": "object",
      "properties": {
        "title": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "League": {
      "type": "object",
      "properties": {
        "format": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "title": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Score": {
      "type": "object",
      "properties": {
        "awayTeam": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        },
        "homeTeam": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "LiveGamePeriod": {
      "type": "object",
      "properties": {
        "name": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "EventInfo": {
      "type": "object",
      "properties": {
        "country": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Country"
            }
          ]
        },
        "teams": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Teams"
            }
          ]
        },
        "league": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/League"
            }
          ]
        },
        "liveGamePeriod": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/LiveGamePeriod"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "state": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "liveMinute": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        },
        "marketsCount": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        },
        "sport": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Sport"
            }
          ]
        },
        "startDate": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "status": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "timeRange": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "LiveScores": {
      "type": "object",
      "properties": {
        "lineEntity": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/LineEntity"
            }
          ]
        },
        "away": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        },
        "gamePeriod": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/GamePeriod"
            }
          ]
        },
        "home": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Country": {
      "type": "object",
      "properties": {
        "title": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Teams": {
      "type": "object",
      "properties": {
        "away": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Team"
            }
          ]
        },
        "home": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "$ref": "#/definitions/Team"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "GamePeriod": {
      "type": "object",
      "properties": {
        "name": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Team": {
      "type": "object",
      "properties": {
        "name": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "LineEntity": {
      "type": "object",
      "properties": {
        "name": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "eventInfo": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "$ref": "#/definitions/EventInfo"
        }
      ]
    },
    "origin": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "$ref": "#/definitions/Origin"
        }
      ]
    },
    "additionalInfo": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "id": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "liveScores": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LiveScores"
          }
        }
      ]
    },
    "typedScores": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "additionalProperties": {
              "$ref": "#/definitions/Score"
            }
          }
        }
      ]
    },
    "timestamp": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    }
  }
}

=== delasport-org/odds-delivery-feed-consumer-example-php/documentation-resources/events/events-live-sample.json
{
  "origin": {
    "stream": "sport",
    "type": "event",
    "environment": "prod",
    "version": "1.0.0"
  },
  "id": "6540840",
  "eventInfo": {
    "id": "6540840",
    "state": "live",
    "status": "running",
    "liveGamePeriod": {
      "name": "2h"
    },
    "liveMinute": 0,
    "marketsCount": 0,
    "startDate": "2023-08-29 11:30:00+0000",
    "timeRange": "today",
    "sport": {
      "id": "1",
      "title": "Football",
      "key": "soccer"
    },
    "country": {
      "id": "1",
      "title": "International"
    },
    "league": {
      "id": "16596",
      "title": "Esoccer Friendly - 15 mins play"
    },
    "teams": {
      "home": {
        "id": "206115",
        "name": "Everton Virtual",
        "color": ""
      },
      "away": {
        "id": "208486",
        "name": "Juventus Virtual",
        "color": ""
      }
    }
  },
  "liveScores": [
    {
      "lineEntity": {
        "id": "1",
        "name": "goals"
      },
      "gamePeriod": {
        "id": "2",
        "name": "ft"
      },
      "home": 0,
      "away": 1
    },
    {
      "lineEntity": {
        "id": "3",
        "name": "red_cards"
      },
      "gamePeriod": {
        "id": "2",
        "name": "ft"
      },
      "home": 0,
      "away": 0
    }
  ],
  "typedScores": {
    "red_cards": {
      "ft": {
        "homeTeam": 0,
        "awayTeam": 0
      }
    },
    "goals": {
      "ft": {
        "homeTeam": 0,
        "awayTeam": 1
      }
    }
  },
  "timestamp": "2023-08-29 11:44:40.347+0000"
}

=== delasport-org/odds-delivery-feed-consumer-example-php/documentation-resources/events/events-early-sample.json
{
  "origin": {
    "stream": "sport",
    "type": "event",
    "environment": "prod",
    "version": "1.0.0"
  },
  "id": "6540840",
  "eventInfo": {
    "id": "6540840",
    "state": "early",
    "status": "not_started",
    "liveGamePeriod": {
      "name": ""
    },
    "liveMinute": 0,
    "marketsCount": 7,
    "startDate": "2023-08-29 11:30:00+0000",
    "timeRange": "today",
    "sport": {
      "id": "1",
      "title": "Football",
      "key": "soccer"
    },
    "country": {
      "id": "1",
      "title": "International"
    },
    "league": {
      "id": "16596",
      "title": "Esoccer Friendly - 15 mins play"
    },
    "teams": {
      "home": {
        "id": "206115",
        "name": "Everton Virtual",
        "color": ""
      },
      "away": {
        "id": "208486",
        "name": "Juventus Virtual",
        "color": ""
      }
    }
  },
  "liveScores": [],
  "typedScores": {},
  "timestamp": "2023-08-29 10:50:16.747+0000"
}
